// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package client is a generated GoMock package.
package client

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	proto "github.com/hovman/ld-proto/pb-service/proto"
)

// MockLanguageDetectionService is a mock of LanguageDetectionService interface.
type MockLanguageDetectionService struct {
	ctrl     *gomock.Controller
	recorder *MockLanguageDetectionServiceMockRecorder
}

// MockLanguageDetectionServiceMockRecorder is the mock recorder for MockLanguageDetectionService.
type MockLanguageDetectionServiceMockRecorder struct {
	mock *MockLanguageDetectionService
}

// NewMockLanguageDetectionService creates a new mock instance.
func NewMockLanguageDetectionService(ctrl *gomock.Controller) *MockLanguageDetectionService {
	mock := &MockLanguageDetectionService{ctrl: ctrl}
	mock.recorder = &MockLanguageDetectionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLanguageDetectionService) EXPECT() *MockLanguageDetectionServiceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockLanguageDetectionService) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockLanguageDetectionServiceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockLanguageDetectionService)(nil).Close))
}

// DetectLanguage mocks base method.
func (m *MockLanguageDetectionService) DetectLanguage(ctx context.Context, text string) (*proto.DetectLanguageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetectLanguage", ctx, text)
	ret0, _ := ret[0].(*proto.DetectLanguageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetectLanguage indicates an expected call of DetectLanguage.
func (mr *MockLanguageDetectionServiceMockRecorder) DetectLanguage(ctx, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetectLanguage", reflect.TypeOf((*MockLanguageDetectionService)(nil).DetectLanguage), ctx, text)
}
